### ISSUE TITLE
[Feature Request] Improve date fields in data lists

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#1807]
### Request Type
Feature Request

### Problem Description
Data objects in TheHive have at least two date fields: `_createAt` and `_updatedAt`. Some objects have additional date fields (`_startDate`, `endDate`, `occurDate` etc...)

In data lists there is no space for all of them with dedicated columns.

### Possible solution

![Screenshot 2021-02-26 at 17 23 07 1](https://user-images.githubusercontent.com/21827/109326342-55172480-7857-11eb-95e2-36f26b343036.png)

### Todo list

- [x] Show all dates in alert list
- [x] Show all dates in case list
- [x] Show all dates in observable list
