### ISSUE TITLE
[Feature Request] Add organisation free tags administration section

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#1816]
### Request Type
Feature Request

### Problem Description
Starting from TheHive 4.1, we introduce support of MISP taxonomies allowing users to import the existing taxonomies definitions that produces a set of predefined tags that can be used in cases, alerts and observables.

We are still supporting free tags (or custom tags), but we need a UI to allow user to manage them.

### Tasks
- [x] Add a UI in org admin section to allow managing existing free tags
- [x] List free tags of the organisation
- [x] Allow tag colour update 
- [x] Add filter, pagination and sort
- [x] Fix custom tag colour display 
- [x] Show free tags usage
- [x] Allow tag delete
- [x] All tag value update

**Comment by crackytsi** [comment]
So it is no longer possible to dynamically add a free tag on an observable or case that hasn't been defined somewhere else before?

We use tons of Tags to add some additional data to observables as Tags that are unique.... 

Thats really breaking :-(

**Comment by nadouani** [comment]
Who said it's not possible :)

Nothing changes, you can do all what you are currently doing with tags

**Comment by crackytsi** [comment]
Ok, thank you Nabil :) That was my (miss-) interpretation when I read the activities arround predefined tags and a new GUI for managing free tags.
