### ISSUE TITLE
[Feature Request] Improve task list page

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#1831]
### Request Type
Feature Request

### Problem Description
The goal of this feature is to track the task list improvements:

- [x] Add bulk actions
  - [x] bulk flag / un flag
  - [x] bulk delete
  - [x] bulk start
  - [x] bulk close
- [x] Rearrange the collapse button
- [x] Create a task flags component
- [x] Rearrange action buttons
  - [x] Allow filtering by flag
  - [x] Allow filtering by status

**Comment by nadouani** [comment]
![Screenshot 2021-03-12 at 07 41 21](https://user-images.githubusercontent.com/21827/110902552-5f7cf800-8306-11eb-93a8-7c221e8acdee.png)

**Comment by jkb-s** [comment]
It's great you add screenshots.   
I hope it's a trend to stay.
