### ISSUE TITLE
Add PAP to case to indicate which kind of action is allowed

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#616]
### Request Type
Feature Request

### Description
PAP (for Permissible Actions Protocol) aims to indicate to analyst the posture to adopt: how much we accept that the attacker detect the current analysis.

As for TLP, PAP is declined in 4 values:
 - RED (3): Non-detectable actions only. Recipients may not use PAP:RED information on the network. Only passive actions on logs, that are not detectable from the outside.
 - AMBER (2): Passive cross check. Recipients may use PAP:AMBER information for conducting online checks, like using services provided by third parties (e.g. VirusTotal), or set up a monitoring honeypot.
 - GREEN (1): Active actions allowed. Recipients may use PAP:GREEN information to ping the target, block incoming/outgoing traffic from/to the target or specifically configure honeypots to interact with the target.
 - WHITE (0): No restrictions in using this information.

### Tasks

- [x] Add `pap` attribute to case class
- [x] Add `pap` attribute to case template class
- [x] Add corresponding mapping migration
- [x] Update case template UI
- [x] Update case details page
- [x] Update case creation dialog
- [x] Update template of case items in search page
- [x] Update template of case items in flow

**Comment by AzureFlameGod** [comment]
Hello,

Is someone currently working on this feature? If so, I would like to figure this out. Please advise.

Respectfully

**Comment by saadkadhi** [comment]
@AzureFlameGod this feature does not exist yet and will be implemented in 3.1. It must not be confounded with the TLP safeguards that analyzers implement (a.k.a `max TLP`).

While the colors in the PAP taxonomy are similar to those of the TLP, they serve a different purpose and are actions that will be applicable to actions you could or could not do during your incident response process depending on the stance you have defined wrt the threat actor you are dealing with.
